import * as Popover from '@radix-ui/react-popover'
import { useState } from 'react'
import { UserRound, ChevronsUpDown, Settings, LogOut } from 'lucide-react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useWorkspace } from '../lib/workspace'
import { call } from '../lib/api'
import type { PageKey } from '../routes'
import { Button, Modal, Input, Select, Tooltip } from './ui'

function readProfile(){try{const data=JSON.parse(localStorage.getItem('legacy.userProfile') ?? '{}');return {name:typeof data?.name==='string' ? data.name : '',email:typeof data?.email==='string' ? data.email : ''}}catch{return {name:'',email:''}}}
export function SidebarUser({collapsed,current,navigate}:{collapsed:boolean;current?:PageKey;navigate(p:PageKey):void}) {
 const {workspace,workspaces,setWorkspaceId}=useWorkspace();const qc=useQueryClient();const [profile,setProfile]=useState(readProfile);const [edit,setEdit]=useState(false);const [logout,setLogout]=useState(false);const [error,setError]=useState('')
 const account=useQuery({queryKey:['instagram-account',workspace.id],queryFn:()=>call('accounts.instagram',{workspaceId:workspace.id})})
 const disconnect=useMutation({mutationFn:()=>call('accounts.disconnectInstagram',{workspaceId:workspace.id}),onSuccess:()=>{void qc.invalidateQueries();setLogout(false)},onError:e=>setError(e instanceof Error?e.message:'Não foi possível sair da conta.')})
 const name=profile.name || (account.data ? `@${account.data.username}` : 'Perfil local')
 const trigger=<Popover.Trigger className="flex w-full items-center gap-2 rounded-ctl p-2 text-left hover:bg-raised" aria-label="Menu do usuário"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-ctl bg-raised"><UserRound size={18}/></span>{!collapsed && <><span className="min-w-0 flex-1"><strong className="block truncate text-xs">{name}</strong><span className="block truncate text-[11px] text-dim">{profile.email || 'E-mail não informado'}</span></span><ChevronsUpDown size={14}/></>}</Popover.Trigger>
 return <><Popover.Root>{collapsed ? <Tooltip content={name}>{trigger}</Tooltip> : trigger}<Popover.Portal><Popover.Content side="right" align="end" sideOffset={8} className="ds-dropdown"><div className="border-b border-line p-2"><strong className="text-sm">{name}</strong><p className="text-xs text-dim">{profile.email || 'Perfil local neste computador'}</p></div><button className="flex w-full gap-2 rounded-ctl p-2 text-sm hover:bg-raised" onClick={()=>setEdit(true)}><UserRound size={16}/>Editar perfil local</button><Popover.Close asChild><button aria-current={current==='settings' ? 'page' : undefined} className="flex w-full gap-2 rounded-ctl p-2 text-sm hover:bg-raised aria-[current=page]:bg-raised" onClick={()=>navigate('settings')}><Settings size={16}/>Configurações</button></Popover.Close><div className="border-y border-line p-2"><Select label="Workspace" value={workspace.id} onChange={e=>setWorkspaceId(e.target.value)}>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</Select></div><button disabled={!account.data} className="flex w-full gap-2 rounded-ctl p-2 text-sm hover:bg-raised disabled:opacity-50" onClick={()=>setLogout(true)}><LogOut size={16}/>Sair da conta Instagram</button></Popover.Content></Popover.Portal></Popover.Root><Modal open={edit} onOpenChange={setEdit} title="Perfil local" description="Identificação neste computador; não altera o perfil do Instagram." footer={<Button variant="primary" onClick={()=>{try{localStorage.setItem('legacy.userProfile',JSON.stringify(profile));setEdit(false)}catch{setError('Não foi possível salvar o perfil.')}}}>Salvar</Button>}><div className="grid gap-3"><Input label="Nome" maxLength={80} value={profile.name ?? ''} onChange={e=>setProfile({...profile,name:e.target.value})}/><Input label="E-mail" type="email" maxLength={254} value={profile.email ?? ''} onChange={e=>setProfile({...profile,email:e.target.value})}/>{error && <p role="alert">{error}</p>}</div></Modal><Modal open={logout} onOpenChange={setLogout} title="Sair da conta Instagram?" description="Desconecta esta conta do workspace e remove o token salvo. Seus arquivos e histórico permanecem; tarefas pendentes não poderão publicar." footer={<><Button onClick={()=>setLogout(false)}>Cancelar</Button><Button variant="danger" loading={disconnect.isPending} onClick={()=>disconnect.mutate()}>Sair</Button></>}>{error && <p role="alert" className="text-danger-fg">{error}</p>}</Modal></>
}
