import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { call } from '../../lib/api'
import { useWorkspace } from '../../lib/workspace'
import { Button, Input, useToast } from '../../components/ui'

export function AccountsPage() {
  const { workspace } = useWorkspace(); const qc = useQueryClient(); const toast = useToast()
  const [token, setToken] = useState('')
  const account = useQuery({ queryKey: ['instagram-account', workspace.id], queryFn: () => call('accounts.instagram', { workspaceId: workspace.id }) })
  const done = () => { void qc.invalidateQueries(); toast.show({ title: 'Conta atualizada' }) }
  const fail = (e: unknown) => toast.show({ title: 'Não foi possível conectar', body: e instanceof Error ? e.message : undefined, tone: 'error' })
  const connect = useMutation({ mutationFn: (value: string) => call('accounts.connectInstagram', { workspaceId: workspace.id, token: value }), onSuccess: done, onError: fail })
  const verify = useMutation({ mutationFn: () => call('accounts.verifyInstagram', { workspaceId: workspace.id }), onSuccess: done, onError: fail })
  const disconnect = useMutation({ mutationFn: () => call('accounts.disconnectInstagram', { workspaceId: workspace.id }), onSuccess: done, onError: fail })
  return <div className="mx-auto flex max-w-3xl min-w-0 flex-col gap-5 p-6"><h1 className="text-xl font-semibold">Contas</h1><section className="rounded-card border border-line bg-panel p-5"><h2 className="font-semibold">Instagram profissional · conexão por token</h2><p className="my-3 text-sm text-dim">Use um token Instagram User de um app Meta com Instagram Login, com instagram_business_basic e instagram_business_content_publish. Use uma conta Business ou Creator.</p><p className="mb-3 text-sm">{account.isLoading ? 'Consultando conta…' : account.data ? `Conectada: @${account.data.username}` : account.isError ? 'Não foi possível consultar a conta.' : 'Nenhuma conta conectada neste workspace.'}</p><ol className="mb-4 grid gap-3 text-sm sm:grid-cols-3"><li>1. Gere o token no painel Meta.</li><li>2. Autorize a conta profissional.</li><li>3. Cole o token e conecte.</li></ol><details className="mb-4 text-xs text-dim"><summary className="cursor-pointer">Ajuda para conectar</summary><p className="mt-2">Em modo de desenvolvimento, adicione sua conta como Testador do Instagram e aceite o convite. Em Configuração da API com login do Instagram, use Gerar token. A chave secreta do app não é um token de usuário. O cadastro verifica identidade; a publicação também exige a permissão content_publish. O navegador estar logado não conecta automaticamente o Legacy.</p><a className="mt-2 block underline" href="https://developers.facebook.com/apps/" target="_blank" rel="noreferrer">Abrir painel Meta</a></details>{account.data && <div className="mb-4 flex flex-wrap items-center gap-3"><Button disabled={verify.isPending} onClick={() => verify.mutate()}>Verificar conexão</Button><span className="text-xs text-dim">Verificada: {new Date(account.data.validatedAt).toLocaleString('pt-BR', { timeZone: workspace.timeZone })}</span></div>}<form className="flex flex-col gap-3" onSubmit={e => { e.preventDefault(); connect.mutate(token, { onSuccess: () => setToken('') }) }}><Input label="Token de acesso Instagram" type="password" autoComplete="off" value={token} onChange={e => setToken(e.target.value)} /><div className="flex flex-wrap gap-2"><Button type="submit" variant="primary" disabled={token.length < 20 || connect.isPending}>Verificar e conectar conta</Button>{account.data && <Button disabled={disconnect.isPending} onClick={() => disconnect.mutate()}>Desconectar conta</Button>}</div></form><p className="mt-4 text-xs text-dim">O token fica protegido pelo Windows e não é exibido novamente. Não há login OAuth pelo navegador nesta versão. Ao trocar ou desconectar a conta, agendamentos anteriores não serão enviados para outro destino. TikTok segue com exportação e postagem manual.</p></section></div>
}
