import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Camera as Instagram, Video, Link2 } from 'lucide-react'
import { call } from '../../lib/api'
import { useWorkspace } from '../../lib/workspace'
import { Button, Input, Modal, Badge, Spinner } from '../../components/ui'
import type { PageProps } from '../../routes'

export function AccountsPage({navigate}: PageProps) {
 const {workspace}=useWorkspace();const qc=useQueryClient()
 const [open,setOpen]=useState(false);const [platform,setPlatform]=useState<'instagram'|'tiktok'|null>(null);const [token,setToken]=useState('');const [error,setError]=useState('');const [disconnectOpen,setDisconnectOpen]=useState(false)
 const account=useQuery({queryKey:['instagram-account',workspace.id],queryFn:()=>call('accounts.instagram',{workspaceId:workspace.id})})
 const done=()=>{void qc.invalidateQueries();setError('');setToken('')}
 const fail=(e:unknown)=>setError(e instanceof Error ? e.message : 'Não foi possível confirmar a conexão. Tente novamente.')
 const connect=useMutation({mutationFn:()=>call('accounts.connectInstagram',{workspaceId:workspace.id,token}),onSuccess:done,onError:fail})
 const verify=useMutation({mutationFn:()=>call('accounts.verifyInstagram',{workspaceId:workspace.id}),onSuccess:done,onError:fail})
 const disconnect=useMutation({mutationFn:()=>call('accounts.disconnectInstagram',{workspaceId:workspace.id}),onSuccess:()=>{done();setDisconnectOpen(false)},onError:fail})
 const changeOpen=(v:boolean)=>{if(connect.isPending)return;setOpen(v);if(!v){setPlatform(null);setToken('');setError('')}}
 return <div className="mx-auto grid max-w-3xl gap-5 p-6"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-semibold">Contas</h1><p className="mt-1 text-sm text-dim">Destinos e permissões do workspace.</p></div><Button icon={<Link2 size={16}/>} onClick={()=>setOpen(true)}>Conectar conta</Button></header><section className="rounded-card border border-line bg-panel p-5"><div className="flex items-center gap-3"><Instagram size={24}/><div className="flex-1"><h2 className="font-semibold">Instagram</h2><p className="mt-1 text-sm text-dim">{account.data ? `@${account.data.username}` : 'Nenhuma conta profissional conectada'}</p></div>{account.isLoading ? <Spinner/> : account.data ? <Badge tone="success">Conectado</Badge> : <Badge>Desconectado</Badge>}</div>{account.isError && <p role="alert" className="mt-3 text-sm text-danger-fg">Não foi possível consultar a conta. <button onClick={()=>void account.refetch()} className="underline">Tentar novamente</button></p>}<div className="mt-4 flex gap-2"><Button onClick={()=>{setPlatform('instagram');setOpen(true)}}>{account.data ? 'Gerenciar' : 'Conectar Instagram'}</Button></div></section><section className="rounded-card border border-line bg-panel p-5"><div className="flex items-center gap-3"><Video size={24}/><div className="flex-1"><h2 className="font-semibold">TikTok</h2><p className="mt-1 text-sm text-dim">Exportação de vídeo, capa e legenda.</p></div><Badge>Manual</Badge></div><Button className="mt-4" onClick={()=>{setPlatform('tiktok');setOpen(true)}}>Ver opções</Button></section><Modal open={open} onOpenChange={changeOpen} title={platform==='instagram' ? 'Conectar Instagram' : platform==='tiktok' ? 'TikTok · exportação manual' : 'Conectar uma conta'} description={platform ? 'Revise o método e as permissões antes de continuar.' : 'Escolha uma plataforma.'} footer={<Button onClick={()=>changeOpen(false)}>Fechar</Button>}>
 {!platform ? <div className="grid gap-3"><button className="ds-choice text-left" onClick={()=>setPlatform('instagram')}><Instagram size={22}/><span><strong>Instagram</strong><span className="mt-1 block text-sm text-dim">Conecte sua conta profissional para publicar Reels e acompanhar publicações.</span></span></button><button className="ds-choice text-left" onClick={()=>setPlatform('tiktok')}><Video size={22}/><span><strong>TikTok</strong><span className="mt-1 block text-sm text-dim">Prepare vídeos para postagem manual. API não configurada.</span></span></button></div> : platform==='tiktok' ? <div className="grid gap-4"><p className="text-sm text-dim">Login Kit e Content Posting API precisam de um app TikTok aprovado. Nenhuma conta será vinculada por esta opção.</p><Button variant="primary" onClick={()=>{changeOpen(false);navigate('compose')}}>Preparar exportação</Button></div> : <div className="grid gap-4">{account.data && <div className="ds-summary">Instagram — @{account.data.username} · Conectado</div>}<div className="rounded-ctl border border-line p-3 text-sm"><strong>Permissões solicitadas</strong><ul className="mt-2 grid gap-1 text-xs text-dim"><li>instagram_business_basic · identidade e mídia</li><li>instagram_business_content_publish · publicação de Reels</li></ul><p className="mt-2 text-xs text-dim">A conexão confirma a identidade. A API também verifica a permissão de publicar na execução.</p></div><p className="text-sm text-dim">Gere um Instagram User Access Token no seu app Meta e autorize uma conta Business ou Creator. Em modo de teste, aceite o convite de Testador do Instagram.</p><a href="https://developers.facebook.com/apps/" target="_blank" rel="noreferrer" className="text-sm underline">Abrir painel Meta para gerar token</a><form className="grid gap-3" onSubmit={e=>{e.preventDefault();setError('');connect.mutate()}}><Input label="Token de acesso Instagram" type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} error={error || undefined}/><Button type="submit" variant="primary" disabled={token.trim().length<20} loading={connect.isPending}>Verificar e conectar conta</Button></form>{account.data && <div className="grid gap-2 border-t border-line pt-3"><p className="text-xs text-dim">Verificada: {new Date(account.data.validatedAt).toLocaleString('pt-BR',{timeZone:workspace.timeZone})}</p><div className="flex flex-wrap gap-2"><Button loading={verify.isPending} onClick={()=>{setError('');verify.mutate()}}>Verificar conexão</Button><Button onClick={()=>setDisconnectOpen(true)}>Desconectar conta</Button></div></div>}<p className="text-xs text-dim">Token protegido pelo Windows. Uma conta por workspace. Trocar o destino não redireciona tarefas antigas. O login no navegador, sozinho, não conecta o Legacy.</p></div>}
 </Modal><Modal open={disconnectOpen} onOpenChange={setDisconnectOpen} title="Desconectar Instagram?" description="O token será removido deste workspace. Agendamentos existentes deixarão de ter autorização; o histórico permanece." footer={<><Button onClick={()=>setDisconnectOpen(false)}>Cancelar</Button><Button variant="danger" loading={disconnect.isPending} onClick={()=>disconnect.mutate()}>Desconectar</Button></>}>{error && <p role="alert" className="text-danger-fg">{error}</p>}</Modal></div>
}
